version: "3.8"

services:
#MariaDB Container
  mariadb:
    image: percona/percona-server:8.0
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=glpidb
      - MARIADB_USER=glpi_user
      - MARIADB_PASSWORD=glpi
    networks:
     - backend
    ports:
     - 3306:3306

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    networks:
     - backend
    depends_on:
     - mariadb

networks:
  backend: