version: "3.8"

services:
#MariaDB Container
  db:
    image: percona/percona-server:8.0
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpi_user
      - MYSQL_PASSWORD=glpi
    networks:
     - backend
    ports:
     - 3306:3306

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    networks:
     - backend
    depends_on:
     - mariadb

networks:
  backend: